version: '3.9'
#コンテナを設定、appとdb
services:
  app:
    build: ./docker
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    depends_on:
      - db
  web:
    image: nginx:1.21.6-alpine
    ports:
        - 34251:80
    volumes:
        - ./src:/var/www
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - app

  db:
    platform: linux/amd64
    image: mysql:8.0.26
    volumes:
      - ./mysql:/var/lib/mysql #データの永続化
    ports:
      - 2435:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpw




  